### ISSUE TITLE
gas optimization in `mint`

### ISSUE THREAD

**Issue by SCBuergel** [modum-io/tokenapp-smartcontract#2]
Depending on the number of investors, the `mint` function might be called many times. To reduce gas usage and delay of token issuance due to many calls, it is important to reduce the gas load to a minimum here. The current version of the contract has a number of guards built in which ensure that the corresponding limits of token numbers do not get exceeded. At the same time, the values of these limits are totally up to the deployer and can be changed arbitrarily. As such, `require`-ing against all these limits does not add additional safeguards as they can be transparently audited by everyone with access to the Ethereum blockchain and everyone can see if the total number of issued tokens exceeds the limits promised in communications by the company.

We therefore suggest to remove all the guards and directly increase the `valueMod` balance of each investor directly. This reduces the computational cost of 29568 gas per address to 21793 (26%). Another 121 gas can be saved by creating temporary variables instead of accessing an index of an array multiple times (`_value[i]` and `_recipient[i]`).

**Comment by tbocek** [comment]
fixed in d06c85eaa0161d0374f814f49882cbef4128f9e9 and d08157acff226c0dec266b3bf56f2f2ecddd5f88
